<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \ZoteroImport\Form\ImportForm $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<?php $form->prepare(); ?>
<?php echo $this->pageTitle($translate('Import from Zotero')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $escape($translate('Submit')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
