<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \ZoteroImport\Api\Representation\ZoteroImportRepresentation $import
 */

$translate = $this->plugin('translate');
?>

<div id="sidebar-confirm">
    <h3><?php echo $translate('Undo Import'); ?></h3>
    <p><?php echo $translate('Are you sure you would like to undo this import? This will delete all imported items.'); ?></p>
    <?php echo $this->form($this->form); ?>
    <h4><?php echo $translate('Zotero Library'); ?></h4>
    <div class="value"><?php echo $import->name(); ?></div>
    <h4><?php echo $translate('Items Added Before'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($import->job()->started(), 'medium', 'medium'); ?></div>
    <h4><?php echo $translate('Job Status'); ?></h4>
    <div class="value"><?php echo $translate($import->job()->statusLabel()); ?></div>
</div>
